service: lambda-orchestrator

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs22.x
  stage: dev
  region: us-east-1
  environment:
    CUSTOMERS_API_BASE: ${env:CUSTOMERS_API_BASE, 'http://localhost:3001'}
    ORDERS_API_BASE: ${env:ORDERS_API_BASE, 'http://localhost:3002'}
    SERVICE_TOKEN: ${env:SERVICE_TOKEN, 'internal-service-token'}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3003
    lambdaPort: 3004

functions:
  createAndConfirmOrder:
    handler: src/handler.createAndConfirmOrder
    events:
      - httpApi:
          method: POST
          path: /orchestrator/create-and-confirm-order
